### ISSUE TITLE
LAPhack 2019 video to Lapikud Youtube

### ISSUE THREAD

**Issue by TerjeRusska** [Lapikud/laphack.eu#31]
https://www.youtube.com/watch?v=fPWqU4sCut8&feature=youtu.be

Needs to be put on Lapikud Youtube account in order to show on the site.

**Comment by artizirk** [comment]
I have uploaded the video here: https://youtu.be/1tjs1PY6xgQ

**Comment by artizirk** [comment]
Its live https://laphack.eu/
