### ISSUE TITLE
Mentoreid tuli juurde

### ISSUE THREAD

**Issue by LiisuxD** [Lapikud/laphack.eu#4]
Mentorite faili kaks viimast, pane Greete Kivi juurde, siis hariduse omad koos :)
Aitäh!

**Comment by artizirk** [comment]
Tutvustuse dokist on väga kehva ja jube tüütu pilte kätte saada, järgmine kord palun lisa pildid eraldi kausta mis on meil täiesti olemas.

**Comment by LiisuxD** [comment]
Mentorid ise panid oma pildid sinna.
